### ISSUE TITLE
Path Settings

### ISSUE THREAD

**Issue by andromeda-0** [Buzz-Beater/LEMMA#1]
Would you please provide a single entry for all path settings?

Currently, there are some entries in `config.py` that do not seem to be used, and some entries in other non-yaml files are linked to directories outside the project dir or the dataset dir (e.g. `/home/baoxiong/models/{}_{}_{}.pyth`).

It would be nice to be able to set all paths solely via command line, yaml files, or a single python script.

Thanks!

**Comment by Buzz-Beater** [comment]
Hi, thanks for your interest and suggestion. So the original idea was to separate project folder set-up with experimental settings but it seems there are overlaps after all. If you don't mind, the only thing to change in config/config.py is the project folder path, annotation, and metadata path. You can change these three paths in config.py and then the whole thing will work out with correct modification in the YAML. For this current version, I guess we will stick with this version and definitely get a better one for the upcoming ones.

**Comment by Buzz-Beater** [comment]
For the extract_feature.py you mentioned, I will try to mention more about how to adjust the paths to run your experiment.
