### ISSUE TITLE
Another way to download dataset?

### ISSUE THREAD

**Issue by Frank-Dz** [Buzz-Beater/LEMMA#2]
Seems like we can not download the dataset from google drive?
![image](https://user-images.githubusercontent.com/55009565/112618038-afa89e00-8e60-11eb-9cf1-69ba1752e79f.png)

Is there another way to download the dataset?

Thank you very much!

**Comment by Buzz-Beater** [comment]
We recently found out about the G-drive download limit mentioned in your screenshot and it is supposed to be a 10TB download quota on a daily basis. We figured it might be enough for hosting the dataset for now, but in the meantime, we are looking for alternative hosts in case the problem you mentioned shows up more often.
