### ISSUE TITLE
Cannot train with multiple gpu

### ISSUE THREAD

**Issue by wqtwjt1996** [Buzz-Beater/LEMMA#4]
I recently run the code with two RTX A6000 gpus:
**python rec_main.py --cfg settings/slowfast_tpv_plain_hoi.yaml EXP.MODEL_TYPE branch EXP.VIEW_TYPE tpv**

I got this error:
**RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!**
even though training with a single GPU is okay.

This is my related environment:
python                    3.8.12               h12debd9_0  
pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
slowfast                  1.0                       dev_0    <develop>
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                py38_cu111    pytorch

This is my selected config setting:
TRAIN:
  ENABLE: True
  DATASET: lemma_seg
  BATCH_SIZE: 32
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: '/usa/wqtwjt/LEMMA/ckpts/SLOWFAST_8x8_R50.pkl'
  CHECKPOINT_TYPE: "caffe2"
  AUTO_RESUME: True
EXP:
  IMG_TYPE: "rgb"
  LABEL_TYPE: "hoi"
  VIEW_TYPE: "fpv"
  MODEL_TYPE: "plain"
  SUPERVISION: "none"
  TASK: "rec"
  VIDEO_TYPE: "all"
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

I also print the "torch.cuda.current_device()" in models/build.py, which always shows "0".

Could you please help me? Thanks!!

**Comment by Buzz-Beater** [comment]
Hi, can you provide the line that caused the error so that I get a better idea?
